[project]
name = "serverless-transcribe"
version = "0.1.0"
description = "Add description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "modal>=1.3.3",
    "requests>=2.32.4",
]
